### ISSUE TITLE
GraphQL/OrderedFields don't work with interfaces.

### ISSUE THREAD

**Issue by alecslupu** [DmitryTsepelev/rubocop-graphql#174]
I do have the following rubocop-graphql config: set in the repo: https://github.com/decidim/decidim

```
require: rubocop-graphql

GraphQL:
  Enabled: true
  Include:
    - "**/lib/decidim/api/**/*"
  Exclude:
    - "**/lib/decidim/api/test/**/*"
    - "**/lib/decidim/api/functions/*"
    - "spec/**/*"
    - "test/**/*"

GraphQL/ObjectDescription:
  Exclude:
    - "**/lib/decidim/api/engine.rb"
    - "**/lib/decidim/api/schema.rb"
    - "**/lib/decidim/api/graphiql/config.rb"
    - "**/lib/decidim/api/functions/*"
    - "spec/**/*"
    - "test/**/*"

GraphQL/ExtractType:
  Enabled: false

```

We have some interfaces defined in : https://github.com/decidim/decidim/tree/develop/decidim-core/lib/decidim/api/interfaces , yet those cannot be sorted.

The spec that needs to pass: 
```
  context "when a unordered field on an interface" do
    it "registers an offense" do
      expect_offense(<<~RUBY)
        module UserInterface
          include GraphQL::Schema::Interface

          field :phone, String, null: true
          field :name, String, null: true
        end
      RUBY

      expect_correction(<<~RUBY)
        module UserInterface
          include GraphQL::Schema::Interface

          field :name, String, null: true
          field :phone, String, null: true
        end
      RUBY
    end
  end
  ```
